server:
  port: 9192

spring:
  datasource:
    username: root
    password: P@sswOrd
    url: jdbc:mysql://localhost:3306/lakeSide_hotel_db
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
